[mypy]
python_version = 3.13
files = app.py, src
mypy_path = src
explicit_package_bases = True
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_optional = True
disable_error_code = import-untyped

[mypy-demo]
ignore_errors = True

[mypy-parse_review]
ignore_errors = True

[mypy-process_data.*]
ignore_errors = True

[mypy-profile]
ignore_errors = True

[mypy-recommend]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
